disable other steps

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -84,20 +84,20 @@ jobs:
       # For patch releases (A.B.C where C != 0), we expect the release to be
       # triggered from the A.B.x maintenance branch. We use the release version
       # without suffixes to avoid mistakes when making pre-releases
-      - name: "Fail if patch release is created from wrong release branch"
-        if: ${{ !endsWith(env.RELEASE_VERSION_WITHOUT_SUFFIX, '.0') && env.RELEASE_BRANCH != github.ref_name }}
-        run: |
-          echo '❌ Release failed due to branch mismatch: expected ${{ inputs.version }} to be released from ${{ env.RELEASE_BRANCH }}, got ${{ github.ref_name }}' >> $GITHUB_STEP_SUMMARY
-          exit 1
+      # - name: "Fail if patch release is created from wrong release branch"
+      #   if: ${{ !endsWith(env.RELEASE_VERSION_WITHOUT_SUFFIX, '.0') && env.RELEASE_BRANCH != github.ref_name }}
+      #   run: |
+      #     echo '❌ Release failed due to branch mismatch: expected ${{ inputs.version }} to be released from ${{ env.RELEASE_BRANCH }}, got ${{ github.ref_name }}' >> $GITHUB_STEP_SUMMARY
+      #     exit 1
 
-      # For non-patch releases (A.B.C where C == 0), we expect the release to
-      # be triggered from main or the A.B.x maintenance branch. This includes
-      # pre-releases for any non-patch releases, e.g. 5.2.0-beta1
-      - name: "Fail if non-patch release is created from wrong release branch"
-        if: ${{ endsWith(env.RELEASE_VERSION_WITHOUT_SUFFIX, '.0') && env.RELEASE_BRANCH != github.ref_name && github.ref_name != 'main' }}
-        run: |
-          echo '❌ Release failed due to branch mismatch: expected ${{ inputs.version }} to be released from ${{ env.RELEASE_BRANCH }} or main, got ${{ github.ref_name }}' >> $GITHUB_STEP_SUMMARY
-          exit 1
+      # # For non-patch releases (A.B.C where C == 0), we expect the release to
+      # # be triggered from main or the A.B.x maintenance branch. This includes
+      # # pre-releases for any non-patch releases, e.g. 5.2.0-beta1
+      # - name: "Fail if non-patch release is created from wrong release branch"
+      #   if: ${{ endsWith(env.RELEASE_VERSION_WITHOUT_SUFFIX, '.0') && env.RELEASE_BRANCH != github.ref_name && github.ref_name != 'main' }}
+      #   run: |
+      #     echo '❌ Release failed due to branch mismatch: expected ${{ inputs.version }} to be released from ${{ env.RELEASE_BRANCH }} or main, got ${{ github.ref_name }}' >> $GITHUB_STEP_SUMMARY
+      #     exit 1
 
       # Set commit author information to the user that triggered the release workflow
       - name: "Set git author information"
