disable curent snapshot version matches

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -66,13 +66,13 @@ jobs:
             echo RELEASE_BRANCH=$(echo ${{ inputs.version }} | awk -F. -v OFS=. '{$NF = "x" ; print}') >> $GITHUB_ENV
           fi
 
-      - name: "Ensure current snapshot version matches release version"
-        run: |
-          grep -q "version=${{ env.RELEASE_VERSION_WITHOUT_SUFFIX }}-SNAPSHOT" gradle.properties
-          if [[ $? != 0 ]]; then
-            echo '❌ Release failed: version in gradle.properties is not a snapshot for release version ${{ inputs.version }}' >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
+      # - name: "Ensure current snapshot version matches release version"
+      #   run: |
+      #     grep -q "version=${{ env.RELEASE_VERSION_WITHOUT_SUFFIX }}-SNAPSHOT" gradle.properties
+      #     if [[ $? != 0 ]]; then
+      #       echo '❌ Release failed: version in gradle.properties is not a snapshot for release version ${{ inputs.version }}' >> $GITHUB_STEP_SUMMARY
+      #       exit 1
+      #     fi
 
       - name: "Ensure release tag does not already exist"
         run: |
